'use strict';

const fs = require('fs/promises');
const path = require('path');

const config = require('../config');
const { prisma } = require('../config/prisma');
const repo = require('../repositories/projectDocumentRepository');
const projectService = require('./projectService');
const dto = require('../dto/projectDocumentDto');
const ApiError = require('../utils/ApiError');
const logger = require('../utils/logger');
const { logEvent } = require('../utils/auditLog');

/**
 * Documents attached to a project: upload them, list them, fetch one back, and
 * remove one.
 *
 * THE RULE THIS FILE EXISTS FOR — a person may only put a document on a project
 * belonging to a company they are associated with. It is enforced in three
 * layers, and each catches something the others cannot:
 *
 *   1. THE PROJECT MUST EXIST AND BE LIVE. A soft-deleted project takes its
 *      upload surface with it.
 *
 *   2. THE CALLER MUST BE ON THAT PROJECT'S COMPANY. Decided by
 *      projectService.loadProjectForRead — the SAME rule that decides whether
 *      they may see the project at all: the owner, a teammate on
 *      `company_members`, the company's accounting manager, or a specialist
 *      actively assigned to the account. An ADMIN is not on that list and gets
 *      the same 403 as a stranger; these are the client's financial records, and
 *      administering the platform is not being party to the work. Nobody outside
 *      the company can name a project id that resolves for them, which is what
 *      makes a guessed id a 403 rather than a disclosure.
 *
 *   3. THE `companyId` IN THE REQUEST MUST MATCH THE PROJECT'S. This grants
 *      nothing — step 2 already settled access — but it catches a client that
 *      has drifted (a stale company selected in one panel, a project chosen in
 *      another) and would otherwise file a document somewhere its user did not
 *      intend. Wrong-but-authorized is exactly the failure a consistency check
 *      is for.
 *
 * WHY THE UNLINKING. Multer writes the bytes before any of this runs — a
 * multipart body cannot be authorized without first being parsed, and the checks
 * above need the database. So a request that is refused has already cost disk,
 * and without cleanup a caller could fill a volume with 403s.
 *
 * That cleanup is `discardUploadedFiles`, and the CONTROLLER calls it, not this
 * file. The reason is that the earliest failure of all — a missing or malformed
 * `companyId` — is raised by the validator, before this service is entered; a
 * try/catch in `uploadDocuments` would miss exactly that case and leak on it.
 * The controller is where every failure path converges, so that is where the
 * cleanup goes.
 */

/* -------------------------------------------------------------------------- */
/* errors                                                                     */
/* -------------------------------------------------------------------------- */

function documentNotFound() {
  return new ApiError(404, 'Document not found.', { code: 'DOCUMENT_NOT_FOUND' });
}

function companyMismatch(projectId) {
  return new ApiError(400, 'That project does not belong to the company you selected.', {
    code: 'PROJECT_COMPANY_MISMATCH',
    fields: { companyId: 'Select the company this project belongs to.' },
    details: { projectId },
  });
}

/* -------------------------------------------------------------------------- */
/* files on disk                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Turn the absolute path multer wrote into the key stored in the database.
 *
 * Always forward slashes, for the same reason userService.toStorageKey
 * normalises: on Windows `path.relative` yields `projects\42\9f3c.pdf`, and that
 * backslash would be carried into the row and then into anything that treats the
 * key as a path fragment. One shape, fixed at the single point where a path
 * becomes a key.
 */
function toStorageKey(absolutePath) {
  return path.relative(config.uploads.documentsDir, absolutePath).split(path.sep).join('/');
}

/**
 * Resolve a stored key back to a path on disk, refusing anything that escapes
 * the documents root.
 *
 * The keys in this column are generated by uploadDocuments middleware and cannot
 * contain `..` — but this is the one function that turns database text into a
 * filesystem read, and a check here costs a string comparison. If the column is
 * ever populated by a migration, a script, or a future code path that is less
 * careful, this is what stops it becoming an arbitrary file read.
 */
function toAbsolutePath(fileKey) {
  const root = path.resolve(config.uploads.documentsDir);
  const resolved = path.resolve(root, fileKey);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw new ApiError(500, 'The stored file could not be located.', { code: 'DOCUMENT_UNREADABLE' });
  }
  return resolved;
}

/**
 * Remove files written for a request that is not going to succeed.
 *
 * Never throws. A failed cleanup must not replace the real error — the caller is
 * already on their way to a 400 or a 403, and telling them "could not unlink"
 * instead would hide the reason their upload was refused.
 */
async function discardUploadedFiles(files, requestId) {
  await Promise.all(
    (files ?? []).map(async (file) => {
      try {
        await fs.unlink(file.path);
      } catch (err) {
        if (err.code !== 'ENOENT') {
          logger.warn(`[${requestId}] Could not remove rejected upload ${file.path}: ${err.message}`);
        }
      }
    })
  );
}

/* -------------------------------------------------------------------------- */
/* what the row records about the file                                        */
/* -------------------------------------------------------------------------- */

// `project_documents.original_name` is VARCHAR(255).
const MAX_NAME_LENGTH = 255;

/**
 * The uploader's own name for the file, made safe to store and to echo back.
 *
 * Three things happen to it, and none of them is cosmetic:
 *
 *   - Any directory part is dropped. Some browsers send a full path for a
 *     drag-and-drop, and "C:\Users\me\tax.pdf" is not a filename. `path.basename`
 *     alone would not catch the Windows form on a POSIX host, hence the split.
 *   - Control characters are stripped. This string is echoed into JSON, into a
 *     Content-Disposition header on download, and into the audit log; a raw
 *     newline in a header is response splitting.
 *   - It is capped at the column width, keeping the extension. Truncating from
 *     the front would turn "…statement.pdf" into "…stateme", which is worse than
 *     useless when the whole point of the field is to tell one file from another.
 *
 * A name that survives none of this (an empty string, or only control
 * characters) falls back to "document" rather than failing the upload — the file
 * is real and the label is decoration.
 */
function toDisplayName(originalName) {
  const base = String(originalName ?? '')
    .split(/[\\/]/)
    .pop();

  // eslint-disable-next-line no-control-regex
  const cleaned = base.replace(/[\u0000-\u001f\u007f]/g, '').trim();
  if (!cleaned) return 'document';
  if (cleaned.length <= MAX_NAME_LENGTH) return cleaned;

  const ext = path.extname(cleaned).slice(0, 20);
  return cleaned.slice(0, MAX_NAME_LENGTH - ext.length) + ext;
}

/* -------------------------------------------------------------------------- */
/* the endpoints                                                              */
/* -------------------------------------------------------------------------- */

/**
 * POST /projects/:projectId/documents — attach one or more files.
 *
 * The request carries the company, the project, and the files; the uploader
 * comes from the token. Everything recorded ABOUT each file — its size, its
 * type, where its bytes are — is measured from the upload rather than taken from
 * the request, so the row cannot describe a file that was never sent.
 *
 * The whole upload is one transaction. Nine files stored and the tenth failing
 * would leave the user looking at a list they cannot explain, with no way to know
 * which of their selection is missing; all or nothing is the only answer they
 * can act on.
 */
async function uploadDocuments({ userId, requestId, projectId, companyId, files }) {
  const { project, company } = await projectService.loadProjectForRead(prisma, {
    userId,
    projectId,
  });

  if (project.companyId !== companyId) throw companyMismatch(projectId);

  const rows = files.map((file) => ({
    projectId: project.id,
    fileKey: toStorageKey(file.path),
    originalName: toDisplayName(file.originalname),
    mimeType: file.mimetype,
    // From the bytes actually written, never from a client-supplied length.
    // BigInt because the column is BIGINT and Prisma will not coerce.
    sizeBytes: BigInt(file.size),
    uploadedByUserId: userId,
  }));

  const documents = await prisma.$transaction(async (tx) => {
    const created = await repo.createDocuments(tx, rows);
    return repo.findDocumentsByIds(tx, created.map((d) => d.id));
  });

  logEvent({
    event: 'project.document.uploaded',
    status: 'success',
    requestId,
    userId,
    companyId: company.id,
    projectId: project.id,
    detail: `${documents.length} file(s), ${rows.reduce((sum, r) => sum + Number(r.sizeBytes), 0)} bytes`,
  });

  return dto.toUploadResult({ projectId: project.id, companyId: company.id, documents });
}

/**
 * GET /projects/:projectId/documents — the attachments panel.
 *
 * Read access to the project is read access to its documents: if you can see
 * that the work exists, you can see what is attached to it. Narrowing this to
 * the uploader would break the case the feature is FOR — a customer uploads a
 * bank statement so that their specialist can open it.
 */
async function listDocuments({ userId, requestId, projectId, query }) {
  const { project, company } = await projectService.loadProjectForRead(prisma, { userId, projectId });

  const { search, limit, offset, sort, order } = query;

  const [documents, summary] = await Promise.all([
    repo.listDocuments(prisma, { projectId: project.id, search, limit, offset, sort, order }),
    repo.summarizeDocuments(prisma, { projectId: project.id, search }),
  ]);

  logEvent({
    event: 'project.document.list.read',
    status: 'success',
    requestId,
    userId,
    companyId: company.id,
    projectId: project.id,
    detail: `${documents.length} document(s)`,
  });

  return dto.toDocumentList({
    documents,
    total: summary._count._all,
    totalBytes: summary._sum.sizeBytes,
    limit,
    offset,
  });
}

/**
 * The document behind GET .../documents/:documentId/download, resolved to a path
 * on disk — authorized first.
 *
 * Returns rather than streams: the controller owns the response, and a service
 * that writes to `res` cannot be called from anywhere else.
 *
 * The document is looked up on its OWN id and then checked against the project
 * in the URL. Fetching it "within" the project would give the same answer to the
 * question that matters, but this way a mismatched pair is a 404 on the document
 * rather than a silent empty result — and the access check that follows is
 * performed on the project the document really belongs to, not the one the URL
 * claimed.
 */
async function getDocumentForDownload({ userId, requestId, projectId, documentId }) {
  const document = await repo.findDocumentForAccess(prisma, documentId);
  if (!document || document.projectId !== projectId || document.project?.deletedAt) {
    throw documentNotFound();
  }

  const { company } = await projectService.loadProjectForRead(prisma, {
    userId,
    projectId: document.projectId,
  });

  const absolutePath = toAbsolutePath(document.fileKey);

  // Confirmed present before the controller starts a response. A missing file is
  // a 404 the client can act on; discovering it mid-stream means the headers are
  // already sent and the download simply truncates.
  try {
    await fs.access(absolutePath);
  } catch {
    logger.error(`[${requestId}] Document ${document.id} has no file at ${document.fileKey}`);
    throw documentNotFound();
  }

  logEvent({
    event: 'project.document.downloaded',
    status: 'success',
    requestId,
    userId,
    companyId: company.id,
    projectId: document.projectId,
    detail: `document ${document.id}`,
  });

  return {
    absolutePath,
    fileName: document.originalName,
    mimeType: document.mimeType,
    sizeBytes: Number(document.sizeBytes),
  };
}

/**
 * DELETE /projects/:projectId/documents/:documentId — soft delete.
 *
 * WHO MAY. Whoever uploaded it, plus anyone with write access to the project
 * (the company's accounting manager, the project's creator, or the assigned
 * specialist). The uploader is on the list because taking back a file
 * you attached by mistake should not require finding a manager; everyone else is
 * on it because they are already responsible for the work the file belongs to.
 *
 * A plain teammate who did not upload it is NOT on the list — they can read the
 * project's documents, and removing someone else's attachment is a different
 * thing from reading it.
 */
async function deleteDocument({ userId, requestId, projectId, documentId }) {
  const document = await repo.findDocumentForAccess(prisma, documentId);
  if (!document || document.projectId !== projectId || document.project?.deletedAt) {
    throw documentNotFound();
  }

  const { caller, project, company } = await projectService.loadProjectForRead(prisma, {
    userId,
    projectId: document.projectId,
  });

  if (document.uploadedByUserId !== caller.id) {
    // Throws PROJECT_ACCESS_DENIED for anyone who is neither the uploader nor
    // responsible for the project.
    projectService.assertWriteAccess(caller, company, project);
  }

  await repo.softDeleteDocument(prisma, document.id, new Date());

  logEvent({
    event: 'project.document.deleted',
    status: 'success',
    requestId,
    userId,
    companyId: company.id,
    projectId: document.projectId,
    detail: `document ${document.id}`,
  });

  return { id: document.id, projectId: document.projectId, deleted: true };
}

module.exports = {
  uploadDocuments,
  listDocuments,
  getDocumentForDownload,
  deleteDocument,
  discardUploadedFiles,
  // Exported for the tests, which check the naming rules directly rather than
  // through a multipart request.
  toDisplayName,
  toStorageKey,
};
