'use strict';

const common = require('./common');
const ApiError = require('../utils/ApiError');

/**
 * Input validation for the project-document endpoints.
 *
 * What is NOT accepted is again the point:
 *
 *   uploadedByUserId    identity comes from the verified access token.
 *   fileKey             generated by the upload middleware. A caller-supplied
 *                       storage path is a path-traversal primitive and a way to
 *                       register a row pointing at somebody else's file.
 *   originalName        read from the multipart part, not from a JSON field —
 *                       so the name recorded is the name of the file that was
 *                       actually sent.
 *   mimeType, sizeBytes measured from the upload. Trusting a client's claim
 *                       about either would let a 40 MB file register itself as
 *                       1 KB, and would defeat the type allowlist.
 *
 * `companyId` IS accepted, and the reason is worth stating because it looks
 * redundant: the project already knows its company. It is required precisely so
 * the two can be COMPARED. The client's request says "file this against company
 * 7, project 42"; if project 42 belongs to company 9, that request expresses a
 * belief about the world that is false, and the honest answer is a 400 rather
 * than quietly filing the document wherever the project happens to live. It is a
 * consistency check, never the thing that grants access — see
 * projectDocumentService.
 */

const UPLOAD_FIELDS = ['companyId'];

const LIMITS = { search: 120 };

/** Columns a caller may sort the documents list by. Never the raw query value. */
const SORTABLE = ['createdAt', 'originalName', 'sizeBytes'];

/**
 * POST /projects/:projectId/documents — the text half of the multipart form.
 *
 * MULTIPART BODIES SKIP THE CASE NORMALISER. `normalizeRequest` runs at app
 * level, before any route middleware, and at that point a multipart request body
 * has not been parsed yet — multer fills `req.body` afterwards. So the
 * `company_id`/`companyId` reconciliation every JSON endpoint gets for free does
 * not happen here, and this function does it itself. Both spellings, but not
 * both at once: sending each with a different value is ambiguous in exactly the
 * way the normaliser refuses, so it is refused the same way.
 */
function validateDocumentUpload(body = {}) {
  const camel = body.companyId;
  const snake = body.company_id;

  const sent = (v) => v !== undefined && v !== null && v !== '';

  if (sent(camel) && sent(snake) && String(camel) !== String(snake)) {
    throw new ApiError(400, 'Send each field once. Received both companyId and company_id.', {
      code: 'VALIDATION_ERROR',
      details: { conflictingFields: ['companyId'] },
    });
  }

  const raw = sent(camel) ? camel : snake;
  if (!sent(raw)) {
    throw new ApiError(400, 'companyId is required.', {
      code: 'VALIDATION_ERROR',
      fields: { companyId: 'Select a company.' },
    });
  }

  // Everything else in the form is refused by name, as elsewhere in this API —
  // a silently ignored field is a client bug that never surfaces. `company_id`
  // is on the allowlist because it is the same field under its other spelling.
  common.rejectUnknown(body, [...UPLOAD_FIELDS, 'company_id']);

  return { companyId: common.parseId(raw, 'companyId') };
}

/** GET /projects/:projectId/documents?search=&limit=&offset=&sort=&order= */
function validateDocumentListQuery(query = {}) {
  common.rejectUnknown(query, ['search', 'limit', 'offset', 'sort', 'order'], 'query string');

  const page = common.pagination(query, {
    defaultLimit: 25,
    maxLimit: 100,
    sortable: SORTABLE,
    defaultSort: 'createdAt',
  });

  return {
    search: query.search ? common.str(query.search, 'search', { max: LIMITS.search }) : null,
    ...page,
    // Newest first. common.pagination already defaults `order` to desc, which is
    // the right way round for an upload date — stated here so the intent is not
    // an accident of the shared default.
    order: query.order ? page.order : 'desc',
  };
}

module.exports = { SORTABLE, LIMITS, validateDocumentUpload, validateDocumentListQuery };
